import { Incident, Authority, AuditLog, EmergencyResource, User } from '../types';

export const INITIAL_USER: User = {
  id: 'usr_citizen_01',
  name: 'Harsha Vardhan',
  email: 'tholetiharshac@gmail.com',
  role: 'citizen',
  location: {
    latitude: 17.385044,
    longitude: 78.486671,
    accuracyMeters: 15,
    address: 'Sector 4, Central District',
    isApproximate: false,
  },
  createdAt: '2026-09-01T08:00:00Z',
};

export const INITIAL_AUTHORITY: Authority = {
  id: 'auth_exec_01',
  organization: 'Disaster Management & Civil Protection Authority',
  role: 'Incident Commander',
  jurisdiction: 'Metro & Regional Emergency Response Zone 1',
};

export const INITIAL_RESOURCES: EmergencyResource[] = [
  {
    id: 'res_1',
    name: 'District General Hospital & Trauma Centre',
    type: 'Hospital',
    address: 'Station Road, North Wing',
    contact: '040-2345-6789 / Toll Free: 108',
    capacity: '48 ICU beds, 120 general emergency beds active',
    latitude: 17.3980,
    longitude: 78.4820,
    available: true,
  },
  {
    id: 'res_2',
    name: 'Central Emergency Relief Shelter #3',
    type: 'Shelter',
    address: 'Govt. Polytechnic Sports Complex',
    contact: 'Control Room: 1077',
    capacity: 'Capacity 650 persons (310 currently accommodated)',
    latitude: 17.3750,
    longitude: 78.4950,
    available: true,
  },
  {
    id: 'res_3',
    name: 'Civil Defence & Fire Rescue Station',
    type: 'Fire Station',
    address: 'Ring Road Junction',
    contact: 'Emergency Dispatch: 101',
    capacity: '4 Quick Response Units, 2 Flood Rescue Inflatable Boats',
    latitude: 17.3910,
    longitude: 78.5020,
    available: true,
  },
  {
    id: 'res_4',
    name: 'Clean Drinking Water & Dry Ration Distribution Point',
    type: 'Food & Water',
    address: 'Municipal Community Centre Ground',
    contact: 'Relief Coordinator: 040-8912-3344',
    capacity: '5000 Litres clean water tanker, 800 ration kits ready',
    latitude: 17.3720,
    longitude: 78.4720,
    available: true,
  },
];

export function getSeedIncidents(centerLat: number, centerLon: number): Incident[] {
  return [
    {
      id: 'INC-2026-081',
      type: 'Flood',
      latitude: centerLat + 0.021, // ~2.3 km North
      longitude: centerLon + 0.015,
      address: 'Low-lying Riverbank Causeway, Bridge Sector 2',
      description: 'Water level breached danger mark by 1.2 meters. Causeway submerged. 3 vehicles stranded, residents evacuating to upper ground.',
      status: 'CONFIRMED',
      severity: 'HIGH',
      confidence: 94,
      createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(), // 45 mins ago
      updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
      reporterId: 'usr_cit_209',
      reporterName: 'K. Ramesh (Local Resident)',
      evidence: [
        {
          id: 'ev_1',
          incidentId: 'INC-2026-081',
          fileUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80',
          fileType: 'image',
          uploadedAt: new Date(Date.now() - 44 * 60 * 1000).toISOString(),
          caption: 'Water surging across causeway roadway near Bridge 2',
        },
      ],
      alertRadiusKm: 5,
      verificationStats: {
        confirmations: 18,
        notPresent: 1,
        unsure: 2,
        totalVerifiers: 21,
      },
    },
    {
      id: 'INC-2026-084',
      type: 'Road blockage',
      latitude: centerLat - 0.038, // ~4.2 km South
      longitude: centerLon - 0.012,
      address: 'Old Trunk Highway Km 14 (Near Hill Cut)',
      description: 'Heavy boulder fall and fallen eucalyptus trees blocking both inbound lanes. Heavy vehicles halted. Traffic diverted to bypass.',
      status: 'CONFIRMED',
      severity: 'MEDIUM',
      confidence: 88,
      createdAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
      reporterId: 'usr_cit_114',
      reporterName: 'S. Patel (Commercial Driver)',
      evidence: [
        {
          id: 'ev_2',
          incidentId: 'INC-2026-084',
          fileUrl: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=800&q=80',
          fileType: 'image',
          uploadedAt: new Date(Date.now() - 108 * 60 * 1000).toISOString(),
          caption: 'Debris and fallen branches obstructing two-way lane',
        },
      ],
      alertRadiusKm: 6,
      verificationStats: {
        confirmations: 12,
        notPresent: 0,
        unsure: 1,
        totalVerifiers: 13,
      },
    },
    {
      id: 'INC-2026-089',
      type: 'Electrical hazard',
      latitude: centerLat + 0.012, // ~1.5 km North-East
      longitude: centerLon - 0.018,
      address: 'Near Old Substation, Market Road',
      description: '11kV high-tension transformer cable snapped and hanging 4 feet above waterlogged sidewalk. Sparking observed during intermittent rain.',
      status: 'UNVERIFIED',
      severity: 'CRITICAL',
      confidence: 62,
      createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
      reporterId: 'usr_cit_310',
      reporterName: 'A. Sharma (Shop Owner)',
      evidence: [
        {
          id: 'ev_3',
          incidentId: 'INC-2026-089',
          fileUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=80',
          fileType: 'image',
          uploadedAt: new Date(Date.now() - 17 * 60 * 1000).toISOString(),
          caption: 'Hanging line over footpath corner near market stall',
        },
      ],
      alertRadiusKm: 3,
      verificationStats: {
        confirmations: 4,
        notPresent: 1,
        unsure: 1,
        totalVerifiers: 6,
      },
    },
    {
      id: 'INC-2026-092',
      type: 'Fire',
      latitude: centerLat + 0.065, // ~7.8 km North-East (In Alert Zone)
      longitude: centerLon + 0.052,
      address: 'Industrial Timber Yard, Plot 44-B',
      description: 'Commercial warehouse structural fire spread across open timber yard. 3 fire tenders on scene. Thick black smoke drifting south-west.',
      status: 'CONFIRMED',
      severity: 'HIGH',
      confidence: 96,
      createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
      reporterId: 'usr_cit_088',
      reporterName: 'Duty Security Officer',
      evidence: [
        {
          id: 'ev_4',
          incidentId: 'INC-2026-092',
          fileUrl: 'https://images.unsplash.com/photo-1543083477-4f785aeafaa9?auto=format&fit=crop&w=800&q=80',
          fileType: 'image',
          uploadedAt: new Date(Date.now() - 178 * 60 * 1000).toISOString(),
          caption: 'Smoke plume visible above industrial shed boundary',
        },
      ],
      alertRadiusKm: 10,
      verificationStats: {
        confirmations: 31,
        notPresent: 2,
        unsure: 0,
        totalVerifiers: 33,
      },
    },
    {
      id: 'INC-2026-095',
      type: 'Landslide',
      latitude: centerLat - 0.095, // ~11.2 km South (Caution Zone)
      longitude: centerLon + 0.041,
      address: 'Ghat Road Section 8, Hill Slopes',
      description: 'Minor earth slip after sustained morning rain. Mud slurry covering outer shoulder. Safe for light vehicles, caution advised for heavy trucks.',
      status: 'CONFIRMED',
      severity: 'LOW',
      confidence: 82,
      createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
      reporterId: 'usr_cit_051',
      reporterName: 'Patrol Officer Mohan',
      evidence: [],
      alertRadiusKm: 15,
      verificationStats: {
        confirmations: 8,
        notPresent: 1,
        unsure: 3,
        totalVerifiers: 12,
      },
    },
  ];
}

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_1',
    actorId: 'auth_exec_01',
    actorName: 'Duty Commander - Civil Protection',
    action: 'CONFIRM_INCIDENT',
    incidentId: 'INC-2026-081',
    details: 'Verified field report via river gauge telemetry and 18 community confirmations. Upgraded to HIGH ALERT.',
    timestamp: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    id: 'aud_2',
    actorId: 'sys_alert_engine',
    actorName: 'Emergency Alert Engine (AWS EventBridge)',
    action: 'BROADCAST_ALERT',
    incidentId: 'INC-2026-081',
    details: 'Dispatched 0-5 km High Alert push to 4,280 registered devices in Bridge Sector 2 perimeter.',
    timestamp: new Date(Date.now() - 39 * 60 * 1000).toISOString(),
  },
  {
    id: 'aud_3',
    actorId: 'auth_exec_01',
    actorName: 'Duty Commander - Civil Protection',
    action: 'SEVERITY_UPDATE',
    incidentId: 'INC-2026-084',
    details: 'Highway blockage severity changed to MEDIUM. Clearing crew dispatched with earthmover equipment.',
    timestamp: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
  },
  {
    id: 'aud_4',
    actorId: 'auth_exec_01',
    actorName: 'Duty Commander - Civil Protection',
    action: 'DISPATCH_CREW',
    incidentId: 'INC-2026-089',
    details: 'Electricity board emergency breakdown van #4 notified for priority isolation of 11kV snapped cable.',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
];
